POST http://localhost:3000/signup
#
# Request Header:
Content-Type: application/json 

# Request Body:
{
  "email": "test@test.com",
  "password": "mypassword"
}

###

GET http://localhost:3000/
Authorization: Bearer xxxxxxxxxxxxxx

###

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "mypassword"
}

###

GET http://localhost:3000/tracks