POST http://localhost:3000/signup
#
# Request Header:
Content-Type: application/json 

# Request Body:
{
  "email": "test@test.com",
  "password": "mypassword"
}

###

GET http://localhost:3000/
Authorization: Bearer xxxxxxxxxxxxxx

###

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "mypassword"
}

###

GET http://localhost:3000/tracks
Authorization: Bearer xxxxxxxxxxxxxx

###

POST http://localhost:3000/tracks
Authorization: Bearer xxxxxxxxxxxxxx
Content-Type: application/json

{
  "name": "My New Track",
  "locations": [
    {
      "timestamp": 123456789,
      "coords": {
        "latitude": 100,
        "longitude": 100,
        "altitude": 100,
        "accuracy": 100,
        "heading": 100,
        "speed": 100
      }
    }
  ]
}